yogi_quotes = [
    "Swing at the strikes.",
    "It ain’t over till it’s over.",
    "It’s déjà vu all over again.",
    "I really didn’t say everything I said.",
    "You can observe a lot just by watching.",
    "The future ain’t what it used to be.",
    "No one goes there nowadays, it’s too crowded.",
    "I usually take a two-hour nap from 1 to 4.",
    "Never answer an anonymous letter.",
    "If you don’t know where you’re going, you might not get there.",
    "We made too many of the wrong mistakes.",
    "You can observe a lot by watching.",
    "It gets late early out here.",
    "If the people don’t want to come out to the ballpark, nobody’s going to stop them.",
    "Baseball is 90 percent mental. The other half is physical.",
    "Pair up in threes.",
    "Why buy good luggage, you only use it when you travel.",
    "All pitchers are liars or crybabies.",
    "A nickel ain’t worth a dime anymore.",
    "Bill Dickey is learning me his experience.",
    "He hits from both sides of the plate. He’s amphibious.",
    "I always thought that record would stand until it was broken.",
    "I can see how he (Sandy Koufax) won 25 games. What I don’t understand is how he lost five.",
    "I never said most of the things I said.",
    "Little League baseball is a very good thing because it keeps the parents off the streets.",
    "You should always go to other people’s funerals, otherwise, they won’t come to yours.",
    "When you come to a fork in the road, take it.",
    "In theory there is no difference between theory and practice. In practice there is.",
    "You don't have to swing hard to hit a home run. If you got the timing, it’ll go.",
    "So I'm ugly. I never saw anyone hit with his face.",
    "Pitching always beats batting — and vice-versa.",
    "If you can't imitate him, don't copy him.",
    "You wouldn’t have won if we’d beaten you.",
    "That's how I kept myself positive, by not getting all negative.",
    "Slump? I ain’t in no slump… I just ain’t hitting.",
    "We're lost, but we're making good time.",
    "Even Napoleon had his Watergate.",
    "A home opener is always exciting, whether it’s at home or on the road.",
    "I knew I was going to take the wrong train, so I left early.",
    "I don't mean to be funny."
    "It ain’t the heat, it’s the humility.",
    "I wish I had an answer to that because I'm tired of answering that question.",
    "90% of the putts that are short don’t go in.",
    "Baseball is a game of confidence, and overcoming failures and fears. That's what life's about too.",
    "The other teams could make trouble for us if they win.",
    "My ambition is to hit .400 and talk 1.000.",
    "It's never happened in the World Series competition, and it still hasn't.",
    "You have to give 100 percent in the first half of the game. If that isn't enough, in the second half, you have to give what's left.",
    "In baseball, you don’t know nothing.",
    "How can you think and hit at the same time?",
    "If I didn’t make it in baseball, I won’t have made it workin’. I didn’t like to work.",
    "If you get a guy that can play a couple of positions, it helps you out a real lot.",
    "I dunno. This game is getting funnier and funnier.",
    "If you don’t catch the ball you catch the bus home.",
]